import type { D1Migration } from 'cloudflare:test'

// Test-only binding injected via `vitest.config.ts`'s `miniflare.bindings` — not part of the
// production `Env` generated by `wrangler types`, so it's merged in here instead of hand-editing
// the generated `src/types/env.d.ts`.
declare global {
  interface Env {
    TEST_MIGRATIONS: D1Migration[]
  }
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[]
    }
  }
}

export {}
