excluded:
  - build_out
  - .build
  - BreakoutGame.xcodeproj

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

disabled_rules:
  - todo

line_length:
  warning: 140
  error: 200

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 600

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - dx
    - dy
    - x
    - y
    - a
    - b

reporter: "xcode"
